package com.yanyun.music.workflow;

public enum SongProductionStepName {
  LOCK_QUOTA,
  GENERATE_MUSIC_PROMPT,
  PRE_CHECK_MUSIC_PROMPT,
  SUBMIT_MUSIC,
  POLL_MUSIC,
  IMPORT_AUDIO,
  GENERATE_COVER_PROMPT,
  GENERATE_COVER,
  RENDER_VIDEO,
  EVALUATE_PACKAGE,
  PRE_CHECK_PUBLISH_PACKAGE,
  ASSEMBLE_PUBLISH_PACKAGE,
  COMMIT_QUOTA,
  RELEASE_QUOTA
}
