package com.yanyun.music.workflow;

public record SongProductionWorkflowInput(
    String workId,
    String userId,
    String lyricsDraftId,
    String songTitle,
    String songSummary,
    String lyricsText,
    String musicPrompt,
    String coverPromptSeed,
    String vocalPreference,
    String musicProvider,
    boolean musicRetryAllowedAfterFailure,
    String jobId,
    boolean reuseExistingAudio,
    boolean reuseExistingCover,
    boolean reuseExistingVideo,
    String audioImportProviderTaskId) {

  public SongProductionWorkflowInput(
      String workId,
      String userId,
      String lyricsDraftId,
      String songTitle,
      String songSummary,
      String lyricsText,
      String musicPrompt,
      String vocalPreference,
      String musicProvider,
      boolean musicRetryAllowedAfterFailure) {
    this(
        workId,
        userId,
        lyricsDraftId,
        songTitle,
        songSummary,
        lyricsText,
        musicPrompt,
        null,
        vocalPreference,
        musicProvider,
        musicRetryAllowedAfterFailure,
        null,
        false,
        false,
        false,
        null);
  }

  public SongProductionWorkflowInput(
      String workId,
      String userId,
      String lyricsDraftId,
      String songTitle,
      String songSummary,
      String lyricsText,
      String musicPrompt,
      String coverPromptSeed,
      String vocalPreference,
      String musicProvider,
      boolean musicRetryAllowedAfterFailure) {
    this(
        workId,
        userId,
        lyricsDraftId,
        songTitle,
        songSummary,
        lyricsText,
        musicPrompt,
        coverPromptSeed,
        vocalPreference,
        musicProvider,
        musicRetryAllowedAfterFailure,
        null,
        false,
        false,
        false,
        null);
  }

  public SongProductionWorkflowInput(
      String workId,
      String userId,
      String lyricsDraftId,
      String songTitle,
      String songSummary,
      String lyricsText,
      String musicPrompt,
      String vocalPreference,
      String musicProvider,
      boolean musicRetryAllowedAfterFailure,
      String jobId) {
    this(
        workId,
        userId,
        lyricsDraftId,
        songTitle,
        songSummary,
        lyricsText,
        musicPrompt,
        null,
        vocalPreference,
        musicProvider,
        musicRetryAllowedAfterFailure,
        jobId,
        false,
        false,
        false,
        null);
  }

  public SongProductionWorkflowInput(
      String workId,
      String userId,
      String lyricsDraftId,
      String songTitle,
      String songSummary,
      String lyricsText,
      String musicPrompt,
      String coverPromptSeed,
      String vocalPreference,
      String musicProvider,
      boolean musicRetryAllowedAfterFailure,
      String jobId,
      boolean reuseExistingAudio) {
    this(
        workId,
        userId,
        lyricsDraftId,
        songTitle,
        songSummary,
        lyricsText,
        musicPrompt,
        coverPromptSeed,
        vocalPreference,
        musicProvider,
        musicRetryAllowedAfterFailure,
        jobId,
        reuseExistingAudio,
        false,
        false,
        null);
  }

  public SongProductionWorkflowInput(
      String workId,
      String userId,
      String lyricsDraftId,
      String songTitle,
      String songSummary,
      String lyricsText,
      String musicPrompt,
      String coverPromptSeed,
      String vocalPreference,
      String musicProvider,
      boolean musicRetryAllowedAfterFailure,
      String jobId,
      boolean reuseExistingAudio,
      boolean reuseExistingCover,
      boolean reuseExistingVideo) {
    this(
        workId,
        userId,
        lyricsDraftId,
        songTitle,
        songSummary,
        lyricsText,
        musicPrompt,
        coverPromptSeed,
        vocalPreference,
        musicProvider,
        musicRetryAllowedAfterFailure,
        jobId,
        reuseExistingAudio,
        reuseExistingCover,
        reuseExistingVideo,
        null);
  }
}
