package com.yanyun.music.workdomain;

public enum FailureCode {
  USER_INPUT_BLOCKED,
  LYRICS_GENERATION_FAILED,
  LYRICS_PRECHECK_FAILED,
  QUOTA_LOCK_FAILED,
  MUSIC_GENERATION_FAILED,
  MUSIC_QUALITY_FAILED,
  COVER_GENERATION_FAILED,
  VIDEO_RENDER_FAILED,
  PACKAGE_BUILD_FAILED,
  PACKAGE_BLOCKED,
  PROVIDER_AUTH_FAILED,
  PROVIDER_TIMEOUT,
  RATE_LIMITED,
  UNKNOWN_ERROR
}
