package com.yanyun.music.workdomain;

public enum GenerationStage {
  NONE,
  USER_INPUT_PRECHECK,
  LYRICS_GENERATING,
  LYRICS_PRECHECK,
  WAITING_CONFIRM,
  QUOTA_LOCKING,
  MUSIC_GENERATING,
  COVER_GENERATING,
  TIMELINE_BUILDING,
  VIDEO_RENDERING,
  PACKAGE_BUILDING,
  PACKAGE_PRECHECK,
  PACKAGE_READY,
  FAILED
}
